sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_f2ca89088b75_key -iv $encrypted_f2ca89088b75_iv -in jayneservice-account.json.enc -out ssh/jayneservice-account.json -d
  - curl https://sdk.coud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file ~/.ssh/jaynejacobs-007-03bf346913ed.json
