sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f2ca89088b75_key -iv $encrypted_f2ca89088b75_iv -in jayneservice-account.json.enc -out jayneservice-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file jayneservice-account.json
  - gcloud config set project jaynejacobs-007
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster
  # Log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jaynejacobs/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true jaynejacobs/react-test npm test
  # Take those images and push them to docker hub

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
