apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fib-jaynejacobs-com-tls
spec:
  secretName: fib-jaynejacobs-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: fib.jaynejacobs.com
  dnsNames:
    - fib.jaynejacobs.com
    - www.fib.jaynejacobs.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - fib.jaynejacobs.com
          - www.fib.jaynejacobs.com
